### ISSUE TITLE
Could u plz provide completed docs for information?

### ISSUE THREAD

**Issue by wiekern** [berndhopp/vaadin-security#1]
The demo code in README not completed and somehow a simple one. I can not dive into writing my own demo. I want to have an access control based on role. Could u provide a complete demo for it?

**Comment by berndhopp** [comment]
Hello Wiekern, sorry for the late answer, I just saw your issue. Which vaadin version are you using? I'm currently working on v10, which will have a pretty simple API for access control, as you can see here: https://github.com/berndhopp/vaadin-security/tree/v10/src/main/java/org/ilay
