### ISSUE TITLE
Support Multiple Authorization Annotations

### ISSUE THREAD

**Issue by Juchar** [berndhopp/vaadin-security#7]
It would be useful to have the possibility to apply multiple annotations to a route.
This way one could use e.g. `@RequiresAuthentication` and `@RequiresAdministrator`.

Of course you could just cram everything into a merged evaluator, but this does not look very clean to me.

**Comment by berndhopp** [comment]
It's hard to see an actual scenario for this, since @RequiresAdministrator would include @RequiresAuthentication by design. Also, multiple annotations would introduce the need for more documentation about processing order, and/or-concatenation.
