### ISSUE TITLE
UserNotInRoleException undocumented

### ISSUE THREAD

**Issue by realulim** [berndhopp/vaadin-security#9]
The code sample on the front page uses a UserNotInRoleException class, which is not part of the framework and there is no explanation where it should come from.

**Comment by berndhopp** [comment]
You are right, it's not well documented. The point here is that Access.restricted(Exception) will eventually delegate to enterEvent#rerouteToError(Exception),

https://github.com/berndhopp/vaadin-security/blob/master/src/main/java/org/ilay/Access.java#L79
